version: "3"

services:
    mssql:
        image: registry.cn-hangzhou.aliyuncs.com/yoyosoft/mssql:2019-latest
        ports:
            - 1438:1433
        volumes:
            - mssqlData:/var/opt/mssql/
        networks:
            - backend
        environment:
            - SA_PASSWORD=bb123456??
            - ACCEPT_EULA=Y

    webapi:
        image: registry.cn-hangzhou.aliyuncs.com/zybdev/blazorapidemo
        ports:
            #- 9898:80
            - 9898:80
            - 3238:3238
        networks:
            - backend
            #- frontend
        environment:
            - WAITHOST=mssql
            - WAITPORT=1433
            - ConnectionStrings__DBConnection=Server=mssql;Database=StudentDb_Blazor;User Id=sa;Password=bb123456??
            - INITDB=true

            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - mssql

    blazor:
        image: registry.cn-hangzhou.aliyuncs.com/zybdev/blazorwebdemo

        networks:
            - backend
            - frontend
        environment:
            - WAITHOST=mssql
            - WAITPORT=1433
            - baseAddress=http://webapi/
            - ConnectionStrings__DBConnection=Server=mssql;Database=StudentDb_Blazor;User Id=sa;Password=bb123456??;
            - DBHOST=mysql
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - mssql

    loadbalancer:
        image: dockercloud/haproxy:latest
        ports:
            - "5000:5000"
            - "1936:1936"
            #- "3238:9898"
            - 3000:80
        environment:
            - DNS_ENABLED=true
            - LOG_LEVEL=info
        links:
            - blazor
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - frontend
            #- backend

volumes:
    mssqlData:

networks:
    frontend:
    backend:
